version: '3.8'

services:
  # Serviço para o MySQL
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trabalhoed1
    ports:
      - "3307:3306" # Porta exposta
    networks:
      - app-network

  # Serviço para a aplicação Spring Boot
  springboot-app:
    image: openjdk:21
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trabalhoed1?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
